model_info:
    model_name: test-mini
    model_version: 1.0
    wandb_project: bgc-infiller
    base_model: facebook/esm2_t6_8M_UR50D

train_params:
    seed: 42
    split_size: 0.2

    epochs: 0.1
    lr: 0.00005
    batch_size: 1
    weight_decay: 0.01
    mlm: 0.15

    save_steps: 1000
    save_total_limit: 2
    logging_steps: 25
    eval_steps: 1000
