name: CI
env:
    WANDB_MODE: "disabled"
on:
    push:
        branches: ["main"]
    pull_request:
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  lfs: true
                  fetch-depth: 0

            - name: Configuración Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Instalación de dependencias
              run: pip install -r requirements.txt

            - name: Ejecución de tests
              env:
                  PYTHONPATH: .
              run: pytest
    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  lfs: true
                  fetch-depth: 0

            - name: Despliegue en Hugging Face
              uses: huggingface/hub-sync@v0.1.0
              with:
                  github_repo_id: ${{ github.repository }}
                  huggingface_repo_id: lm-jim/bgc-infiller
                  hf_token: ${{ secrets.HF_TOKEN }}
                  repo_type: space
                  subdirectory: space
